/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.io.IOException;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import kontroler.Controller;
import model.Korisnik;
import model.Prevoz;
import model.Putovanje;

/**
 *
 * @author Milica
 */
public class DodajPutovanjeForma extends javax.swing.JFrame {

    private Putovanje p;
    private KorisnikForma aThis;
    private Korisnik ulogovani;
    private Korisnik k;
    private KorisnikForma kf;

    /**
     * Creates new form DodajPutovanjeForma
     */
    public DodajPutovanjeForma() {
        initComponents();
        setLocationRelativeTo(null);
        popuniComboBox();
//        btnDodaj.setVisible(false);
        btnIzmeni.setVisible(false);
    }

    public DodajPutovanjeForma(Korisnik k, KorisnikForma kf) {
        initComponents();
        setLocationRelativeTo(null);
        popuniComboBox();
        this.ulogovani = k;
        this.kf = kf;
        btnMeni.setVisible(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        btnIzmeni.setVisible(false);

        txtIme.setText(ulogovani.getIme());
        txtPrezime.setText(ulogovani.getPrezime());
        txtJmbg.setText(ulogovani.getJmbg());
        txtPasos.setText(ulogovani.getPasos());
        txtIme.setEditable(false);
        txtPrezime.setEditable(false);
        txtJmbg.setEditable(false);
        txtPasos.setEditable(false);

    }

    public DodajPutovanjeForma(KorisnikForma aThis, Putovanje p, Korisnik ulogovani) {
        initComponents();
        setLocationRelativeTo(null);
        popuniComboBox();
        btnMeni.setVisible(false);
        popuni(p);
        this.p = p;
//        this.aThis = aThis;
        this.kf = aThis;
        this.setLocationRelativeTo(null);
        this.ulogovani = ulogovani;

        aThis.popuniTabelu();

        btnDodaj.setVisible(false);

        txtIme.setText(ulogovani.getIme());
        txtPrezime.setText(ulogovani.getPrezime());
        txtJmbg.setText(ulogovani.getJmbg());
        txtPasos.setText(ulogovani.getPasos());
        txtIme.setEditable(false);
        txtPrezime.setEditable(false);
        txtJmbg.setEditable(false);
        txtPasos.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtJmbg = new javax.swing.JTextField();
        txtZemlje = new javax.swing.JTextField();
        txtDatumUlaska = new javax.swing.JTextField();
        txtDatumIzlaska = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnDodaj = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPasos = new javax.swing.JTextField();
        btnMeni = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("DODAJ PUTOVANJE");

        jLabel2.setText("IME:");

        jLabel3.setText("PREZIME:");

        jLabel4.setText("JMBG:");

        jLabel5.setText("ZEMLJA:");

        jLabel6.setText("Datum ulaska u EU:");

        jLabel7.setText("Datum izlaska iz EU:");

        jLabel8.setText("Način prevoza:");

        txtPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeActionPerformed(evt);
            }
        });

        txtDatumUlaska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumUlaskaActionPerformed(evt);
            }
        });

        txtDatumIzlaska.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumIzlaskaActionPerformed(evt);
            }
        });

        btnDodaj.setText("DODAJ PUTOVANJE");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jLabel9.setText("BROJ PASOSA:");

        txtPasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasosActionPerformed(evt);
            }
        });

        btnMeni.setText("MENI");
        btnMeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeniActionPerformed(evt);
            }
        });

        btnIzmeni.setText("izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnDodaj)
                .addGap(59, 59, 59)
                .addComponent(btnMeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(94, 94, 94)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumUlaska))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJmbg)
                            .addComponent(txtZemlje)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPasos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtDatumIzlaska)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtZemlje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDatumUlaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDatumIzlaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnIzmeni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnMeni))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private void txtDatumUlaskaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumUlaskaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumUlaskaActionPerformed

    private void txtDatumIzlaskaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumIzlaskaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumIzlaskaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        // TODO add your handling code here:

        System.out.println("Kliknuto dugme Dodaj!");

        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String jmbg = txtJmbg.getText().trim();
        String pasos = txtPasos.getText().trim();
        String zemlje = txtZemlje.getText().trim();

        Prevoz prevoz = (Prevoz) jComboBox1.getSelectedItem();

        // datum ulaska / datum izlaska / uslov za datume / prekoracenje - 90 dana
        LocalDate ulazakEu;
        LocalDate izlazakEu;
        try {
            ulazakEu = LocalDate.parse(txtDatumUlaska.getText(), DateTimeFormatter.ofPattern("dd.MM.yyyy."));
            izlazakEu = LocalDate.parse(txtDatumIzlaska.getText(), DateTimeFormatter.ofPattern("dd.MM.yyyy."));

            // da li su sva polja popunjena
            if (ime.equals("") || prezime.equals("") || jmbg.equals("") || pasos.equals("") || zemlje.equals("")
                    || ulazakEu.equals("") || izlazakEu.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Svi podaci moraju biti uneti!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // datum ulaska ne  pre danas
            if (ulazakEu.isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(rootPane, "Datum ulaska ne može biti pre današnjeg datuma!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // datum izlaska ne pre datuma ulaska
            if (izlazakEu.isBefore(ulazakEu)) {
                JOptionPane.showMessageDialog(rootPane, "Datum izlaska ne može biti pre datuma ulaska!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // max 90 dana boravka
            long brojDana = ChronoUnit.DAYS.between(ulazakEu, izlazakEu) + 1; // plus jedna za dan kad udje u eu
            if (brojDana > 90) {
                JOptionPane.showMessageDialog(rootPane, "Korisnik može da se zadrži maksimalno 90 dana na putovanju!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Datum mora biti u formatu dd.MM.yyyy.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // jmbg validacija 
        if (jmbg.length() != 13) {
            JOptionPane.showMessageDialog(rootPane, "JMBG mora imati tacno 13 cifara!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Long.parseLong(jmbg); //provera za cifre 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "JMBG mora sadržati samo cifre!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //broj pasosa validacija
        if (pasos == null) {
            JOptionPane.showMessageDialog(rootPane, "Unesite ispravan broj pasoša !", "Broj pasoša-Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int length = pasos.length();
        if (length < 8 || length > 9) {
            JOptionPane.showMessageDialog(rootPane, "Broj pasoša mora imati 8 ili 9 karaktera!", "Broj pasoša-Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //  svi karakteri velika slova ili cifre
        for (int i = 0; i < length; i++) {
            char c = pasos.charAt(i);
            if (!((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))) {
                JOptionPane.showMessageDialog(rootPane, "Broj pasoša mora sadržati samo velika slova i cifre!", "Broj pasoša-Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (zemlje == null) {
            JOptionPane.showMessageDialog(this, "Unesite drzavu", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Putovanje p = new Putovanje(ime, prezime, jmbg, pasos, zemlje, ulazakEu, izlazakEu, prevoz);

        try {
            if (Controller.getInstance().dodaj_putovanje(p)) {
                JOptionPane.showMessageDialog(this, "Uspesno ste dodali putovanje!", "USPESNO!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Jmbg ne postoji u bazi ili vec postoji putovanje u datom periodu!","Greska!",JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(DodajPutovanjeForma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(DodajPutovanjeForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDodajActionPerformed

    private void txtPasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasosActionPerformed

    private void btnMeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeniActionPerformed
        // TODO add your handling code here:
//        KlijentskaForma kf = new KlijentskaForma();
//        kf.setVisible(true);
//        this.dispose();

        this.dispose();
    }//GEN-LAST:event_btnMeniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // TODO add your handling code here:
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String jmbg = txtJmbg.getText().trim();
        String pasos = txtPasos.getText().trim();
        String zemlje = txtZemlje.getText().trim();

        Prevoz prevoz = (Prevoz) jComboBox1.getSelectedItem();

        // datum ulaska / datum izlaska / uslov za datume / prekoracenje - 90 dana
        LocalDate ulazakEu;
        LocalDate izlazakEu;
        try {
            ulazakEu = LocalDate.parse(txtDatumUlaska.getText(), DateTimeFormatter.ofPattern("dd.MM.yyyy."));
            izlazakEu = LocalDate.parse(txtDatumIzlaska.getText(), DateTimeFormatter.ofPattern("dd.MM.yyyy."));

            // datum ulaska ne  pre danas
            if (ulazakEu.isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(rootPane, "Datum ulaska ne može biti pre današnjeg datuma!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // datum izlaska ne pre datuma ulaska
            if (izlazakEu.isBefore(ulazakEu)) {
                JOptionPane.showMessageDialog(rootPane, "Datum izlaska ne može biti pre datuma ulaska!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // max 90 dana boravka
            long brojDana = ChronoUnit.DAYS.between(ulazakEu, izlazakEu) + 1; // plus jedna za dan kad udje u eu
            if (brojDana > 90) {
                JOptionPane.showMessageDialog(rootPane, "Korisnik može da se zadrži maksimalno 90 dana na putovanju!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Datum mora biti u formatu dd.MM.yyyy.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        p.setZemlje(zemlje);
        p.setDatumIzlaska(izlazakEu);
        p.setDatumUlaska(ulazakEu);
        p.setNacinPrevoza(prevoz);

        try {
            Controller.getInstance().izmeniPutovanje(p);
            kf.popuniTabelu();
            JOptionPane.showMessageDialog(null, "Uspesna izmena");
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(DodajPutovanjeForma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(DodajPutovanjeForma.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnMeni;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDatumIzlaska;
    private javax.swing.JTextField txtDatumUlaska;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtPasos;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtZemlje;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        jComboBox1.setModel(new DefaultComboBoxModel(Prevoz.values()));
    }

    private void popuni(Putovanje p) {
        txtZemlje.setText(p.getZemlje());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy.");
        txtDatumIzlaska.setText(p.getDatumIzlaska().format(formatter));
        txtDatumUlaska.setText(p.getDatumUlaska().format(formatter));
        jComboBox1.setSelectedItem(p.getNacinPrevoza());

    }
}
